#!/usr/bin/env lua
--[[-----------------------------------------------------------------------------
Usage:
-- place on top of the script
#!/usr/bin/env lua-wow-shebang
-------------------------------------------------------------------------------]]
local verbose = false

--[[-----------------------------------------------------------------------------
Global Functions
-------------------------------------------------------------------------------]]
function deployerHome() return os.getenv('DEPLOYER_HOME') end
function invokedAs() return os.getenv('ALIAS_NAME') end

--[[-----------------------------------------------------------------------------
Start
-------------------------------------------------------------------------------]]
local s = '[lua-wow-shebang]:: '
local function p(...) print(s, ...) end
if verbose then p('verbose=', verbose) end

local install_dir = deployerHome()
if not install_dir then return end

-- Set up module paths
local paths = {
    install_dir .. "/lua/lib/?.lua",
    install_dir .. "/lua/?.lua",
    install_dir .. "/lua/?/init.lua",
    package.path,
}; package.path = table.concat(paths, ";")

if verbose then
  p(s, 'script=', arg[1])
  p(s, 'install_dir=', install_dir)
  p(s, 'package.path=', package.path)
end

local script = arg[1]
if not script then
  p("Usage: Add this shebang in your lua script: #!/usr/bin/env lua-wow-shebang")
  os.exit(1)
end

table.remove(arg, 1) -- Remove script name from args
dofile(script)
